'use strict';
/*
 * mapdb.js -- which map is the player standing in, and where is its origin.
 *
 * MegaSkywars keeps all 31 maps in the single world "world" at hardcoded
 * origins >= 1724 blocks apart (MapManager.addMaps), and the .mworld scans are
 * spawn-relative to exactly those origins. So identifying the map is a nearest-
 * origin lookup on the player's absolute position, and converting to the
 * console's coordinate space is a subtraction. That is the whole reason the
 * console needs no chunk decoder.
 *
 * proxy/mapdb.json is generated by tools/gen_mapdb.py, which also asserts the
 * parts of that assumption checkable without a live server: every scan sits
 * inside 0..255 at its origin, and no two maps overlap. The part that still
 * needs the live server -- that the XZ axes are not mirrored, which a
 * symmetric map would hide -- is one distinctive block per map, and the
 * `describeAt` helper below is what to check it with.
 */

const fs = require('fs');
const path = require('path');

class MapDB {
    constructor(doc) {
        this.margin = doc.margin || { xz: 0, y: 0 };
        this.maps = doc.maps.map((m) => {
            const [ox, oy, oz] = m.origin;
            // Absolute bounds, margin included: a block placed on a bridge out
            // past the scan is still this map's block and still fits on the
            // console, so the acceptance box has to be the padded one.
            const lo = [m.min[0] - this.margin.xz, m.min[1] - this.margin.y,
                        m.min[2] - this.margin.xz];
            const hi = [m.min[0] + m.dim[0] - 1 + this.margin.xz,
                        m.min[1] + m.dim[1] - 1 + this.margin.y,
                        m.min[2] + m.dim[2] - 1 + this.margin.xz];
            return Object.assign({}, m, {
                originX: ox, originY: oy, originZ: oz,
                absMin: [lo[0] + ox, lo[1] + oy, lo[2] + oz],
                absMax: [hi[0] + ox, hi[1] + oy, hi[2] + oz],
                localMin: lo, localMax: hi,
            });
        });
        this.byName = new Map(this.maps.map((m) => [m.name, m]));
    }

    get(name) { return this.byName.get(name) || null; }
    get size() { return this.maps.length; }

    /**
     * The map an absolute position belongs to, or null for the hub. Inside a
     * map's padded box is decisive; otherwise the nearest origin within
     * `radius` wins, which covers the seconds around a teleport when the
     * player is above or beside the geometry rather than in it. Origins are
     * 1724 blocks apart and no scan reaches further than 175 from its own, so
     * a few hundred blocks of slack is unambiguous.
     */
    findByPosition(x, y, z, radius = 250) {
        for (const m of this.maps) {
            if (x >= m.absMin[0] && x <= m.absMax[0] &&
                y >= m.absMin[1] && y <= m.absMax[1] &&
                z >= m.absMin[2] && z <= m.absMax[2]) return m;
        }
        let best = null, bestD = radius * radius;
        for (const m of this.maps) {
            const dx = x - m.originX, dz = z - m.originZ;
            const d = dx * dx + dz * dz;
            if (d < bestD) { bestD = d; best = m; }
        }
        return best;
    }

    /** Does an absolute position fall inside this map's padded box? */
    static contains(m, x, y, z) {
        return x >= m.absMin[0] && x <= m.absMax[0] &&
               y >= m.absMin[1] && y <= m.absMax[1] &&
               z >= m.absMin[2] && z <= m.absMax[2];
    }

    /** For the one check that needs a live server: print a coordinate in both
     *  spaces so a block can be compared against the running game. */
    static describeAt(m, x, y, z) {
        return `${m.name}: absolute (${x}, ${y}, ${z}) = local ` +
               `(${x - m.originX}, ${y - m.originY}, ${z - m.originZ})`;
    }
}

function load(file = path.join(__dirname, 'mapdb.json')) {
    try {
        return new MapDB(JSON.parse(fs.readFileSync(file, 'utf8')));
    } catch (e) {
        throw new Error(`cannot read ${file} (run: python tools/gen_mapdb.py)` +
                        `\n  ${e.message}`);
    }
}

module.exports = { load, MapDB };
