#!/usr/bin/env python3
"""
build_font.py -- bake Minecraft 1.8.9's ASCII glyph sheet into a GameCube
texture plus the variable-width table that goes with it.

Source is MCP-919's `assets/minecraft/textures/font/ascii.png`: a 128x128 sheet
holding a 16x16 grid of 8x8 glyph cells, white pixels on transparent. For the
printable ASCII range this engine draws (32..126) a character's cell index is
simply its character code -- that is the slice of `FontRenderer`'s
`field_111274_c` ordering string where the accented/box-drawing pages have not
started yet -- so no indirection table is needed.

Output: <data>/font.png   (fed to gxtexconv -> font.tpl by the bake step below)
        <src>/font_gen.h  (glyph advances + sheet geometry)

**Format.** The sheet is written as an *intensity* image, R=G=B=the source
alpha, and converted to GX's I4 (4 bits/texel, 8 KB for the whole sheet).
GX expands an I4 texel to (I,I,I,I) -- intensity in alpha as well as colour --
so one 4-bit channel carries the whole glyph mask, and `GX_MODULATE` against
the vertex colour gives arbitrarily coloured, correctly cut-out text with no
second texture channel. Writing intensity from *alpha* rather than letting
gxtexconv take the luminance of an RGBA image is what makes that true
regardless of what colour the sheet's transparent pixels happen to carry.

No mipmaps: the HUD draws glyphs at an integer GUI scale through GX_NEAR, and
a mip chain would only blur them.

**Widths.** Transcribed from `FontRenderer.readFontTexture()`: scan each cell
right-to-left for the first column with any non-transparent pixel, and the
advance is that column's index + 1, +1 again for the inter-glyph gap. Space is
an empty cell, which that rule would make 1 wide; vanilla instead hardcodes 4
in `renderCharAtPos`, so this emits 4 and hud.c needs no special case.

Usage:  build_font.py [ascii.png] [data-dir]
Bake:   gxtexconv -i font.png -o font.tpl colfmt=0 mipmap=no
        (then delete the font.png/font.h gxtexconv leaves behind)
"""
import os
import sys
from PIL import Image

# 16x16 grid of 8x8 cells. Derived from the source image below, but asserted
# against these so a differently-sized sheet fails loudly rather than baking
# garbled glyphs.
GRID = 16
CELL = 8

FIRST_CHAR = 32     # ' '
LAST_CHAR = 126     # '~'
SPACE_WIDTH = 4     # FontRenderer.renderCharAtPos hardcodes 4.0F for ' '

SRC = (r"C:\Users\awt12\Downloads\MCP-919-main\MCP-919-main\temp\src\minecraft"
       r"\assets\minecraft\textures\font\ascii.png")


def glyph_width(alpha, cell_px, cx, cy):
    """FontRenderer.readFontTexture's per-cell scan: walk columns from the
    right, stop at the first one with any opaque pixel, advance = index + 1
    (+1 for the gap the renderer leaves between glyphs)."""
    col = cell_px - 1
    while col >= 0:
        x = cx * cell_px + col
        if any(alpha[x, cy * cell_px + row] != 0 for row in range(cell_px)):
            break
        col -= 1
    col += 1
    # vanilla scales by 8/cellWidth for sheets wider than 128; == 1 here
    return int(0.5 + col * (8.0 / cell_px)) + 1


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else SRC
    data_dir = sys.argv[2] if len(sys.argv) > 2 else \
        os.path.join(os.path.dirname(__file__), "..", "data")
    data_dir = os.path.abspath(data_dir)
    src_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "source"))

    im = Image.open(src).convert("RGBA")
    assert im.width == im.height, f"expected a square sheet, got {im.size}"
    assert im.width % GRID == 0, f"{im.width}px sheet is not a {GRID}x{GRID} grid"
    cell_px = im.width // GRID
    assert cell_px == CELL, f"expected {CELL}px cells, got {cell_px}"

    alpha = im.getchannel("A").load()

    widths = [glyph_width(alpha, cell_px, ch % GRID, ch // GRID)
              for ch in range(FIRST_CHAR, LAST_CHAR + 1)]
    widths[0] = SPACE_WIDTH

    # Intensity image: I = source alpha, so gxtexconv's luminance pass lands
    # exactly on the glyph mask (see the format note above).
    out = Image.new("RGB", im.size)
    op = out.load()
    for y in range(im.height):
        for x in range(im.width):
            a = alpha[x, y]
            op[x, y] = (a, a, a)
    png = os.path.join(data_dir, "font.png")
    out.save(png)

    hpath = os.path.join(src_dir, "font_gen.h")
    with open(hpath, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/build_font.py -- do not edit. */\n")
        f.write("#ifndef MSW_FONT_GEN_H\n#define MSW_FONT_GEN_H\n\n")
        f.write("/* Minecraft 1.8.9's ascii.png, baked to I4 as data/font.tpl.\n")
        f.write(" * A character's cell index is its own code for the printable\n")
        f.write(" * ASCII range below -- see tools/build_font.py. */\n")
        f.write(f"#define FONT_CELL {cell_px}\n")
        f.write(f"#define FONT_GRID {GRID}\n")
        f.write(f"#define FONT_TEX_W {im.width}\n")
        f.write(f"#define FONT_TEX_H {im.height}\n")
        f.write(f"#define FONT_FIRST_CHAR {FIRST_CHAR}\n")
        f.write(f"#define FONT_LAST_CHAR {LAST_CHAR}\n")
        f.write(f"#define FONT_CHAR_COUNT {LAST_CHAR - FIRST_CHAR + 1}\n\n")
        f.write("/* FontRenderer.charWidth: the pen advance for each glyph,\n")
        f.write(" * indexed by (char - FONT_FIRST_CHAR). Includes the 1px gap\n")
        f.write(" * the renderer leaves between glyphs; the drawn quad is always\n")
        f.write(" * FONT_CELL wide, so a glyph may overhang its own advance. */\n")
        f.write("static const u8 g_fontWidth[FONT_CHAR_COUNT] = {\n")
        for row in range(0, len(widths), 24):
            f.write("\t" + ",".join(str(w) for w in widths[row:row + 24]) + ",\n")
        f.write("};\n\n")
        f.write("#endif\n")

    print(f"font: {im.width}x{im.height}, {cell_px}px cells -> {png}")
    print(f"  wrote {hpath} ({len(widths)} glyphs, "
          f"widths {min(widths)}..{max(widths)})")
    print(f"  bake: gxtexconv -i font.png -o font.tpl colfmt=0 mipmap=no")


if __name__ == "__main__":
    main()
