#!/usr/bin/env python3
"""
build_entity_tex.py -- stage the two entity skins the console renders and emit
the geometry constants that go with them.

T9 needs a player skin and T12 an ender dragon, and neither can live in
`data/atlas.tpl`: the atlas is a grid of padded 16x16 cells, and a skin's UV
layout is one unwrapped sheet whose boxes straddle those cell boundaries.  So
each gets its own small TPL, exactly as the font does.

Source is MCP-919's vanilla assets:

    entity/steve.png                64x64   the default player skin
    entity/enderdragon/dragon.png   256x256

`steve.png` in 1.8.9 is the 64x64 layout, but every offset `ModelBiped` uses
(head 0,0 / body 16,16 / arm 40,16 / leg 0,16) lives in the top 32 rows, which
is byte-identical to the old 64x32 sheet -- the bottom half is the second skin
layer and the separated left limbs, neither of which the 6-box model draws.
The whole sheet is baked anyway because it costs 8 KB and cropping it would
make the UV constants disagree with vanilla's.

**Format: RGB5A3.**  16 bits a texel with 3 bits of alpha, the same choice T4
made for the atlas.  Both sheets are alpha-cutout only -- the skin's hat layer
and the dragon's wing membrane are either fully opaque or fully transparent --
and the entity shader is an alpha *test*, not a blend, so 3 bits of alpha is 3
more than are needed.  Costs 8 KB for the skin and 128 KB for the dragon
against a heap the perf overlay reports in megabytes.

No mipmaps: vanilla ships none for entities either, and the models are drawn
at close enough range that a mip chain would only cost memory.

Output: <data>/steve.png, <data>/dragon.png   (staged for gxtexconv)
        <src>/entity_tex_gen.h                (sheet dimensions)

Usage:  build_entity_tex.py [mcp-assets-dir] [data-dir]
Bake:   gxtexconv -i steve.png  -o steve.tpl  colfmt=5 mipmap=no
        gxtexconv -i dragon.png -o dragon.tpl colfmt=5 mipmap=no
        (then delete the .png/.h gxtexconv leaves behind in data/)
"""
import os
import sys
from PIL import Image

ASSETS = (r"C:\Users\awt12\Downloads\MCP-919-main\MCP-919-main\temp\src"
          r"\minecraft\assets\minecraft\textures\entity")

# name -> (relative path under ASSETS, expected size). The sizes are asserted
# rather than read: every UV constant in entity.c is a literal pixel offset
# into these exact sheets, so a resource pack's higher-resolution replacement
# would silently unwrap every box wrong.
SHEETS = {
    "steve":  ("steve.png", (64, 64)),
    "dragon": (os.path.join("enderdragon", "dragon.png"), (256, 256)),
}


def stage(src_dir, data_dir, name, rel, expect):
    src = os.path.join(src_dir, rel)
    im = Image.open(src).convert("RGBA")
    assert im.size == expect, f"{rel}: expected {expect}, got {im.size}"

    # RGB5A3 stores 3 bits of alpha in the translucent encoding and none in the
    # opaque one, so anything between the two ends is a rounding accident
    # waiting to happen against a GEQUAL 128 alpha test. Snap it here, where it
    # is visible, rather than in gxtexconv's quantiser.
    a = im.getchannel("A").point(lambda v: 255 if v >= 128 else 0)
    im.putalpha(a)

    out = os.path.join(data_dir, name + ".png")
    im.save(out)
    return out, im.size


def main():
    src_dir = sys.argv[1] if len(sys.argv) > 1 else ASSETS
    data_dir = sys.argv[2] if len(sys.argv) > 2 else \
        os.path.join(os.path.dirname(__file__), "..", "data")
    data_dir = os.path.abspath(data_dir)
    gen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "source"))

    sizes = {}
    for name, (rel, expect) in SHEETS.items():
        out, size = stage(src_dir, data_dir, name, rel, expect)
        sizes[name] = size
        print(f"{name}: {size[0]}x{size[1]} -> {out}")

    hpath = os.path.join(gen_dir, "entity_tex_gen.h")
    with open(hpath, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/build_entity_tex.py -- do not edit. */\n")
        f.write("#ifndef MSW_ENTITY_TEX_GEN_H\n#define MSW_ENTITY_TEX_GEN_H\n\n")
        f.write("/* Sheet dimensions for the entity skins baked to RGB5A3 as\n")
        f.write(" * data/steve.tpl and data/dragon.tpl. entity.c's box UVs are\n")
        f.write(" * vanilla's pixel offsets into these exact sheets. */\n")
        for name in sorted(sizes):
            w, h = sizes[name]
            f.write(f"#define {name.upper()}_TEX_W {w}\n")
            f.write(f"#define {name.upper()}_TEX_H {h}\n")
        f.write("\n#endif\n")
    print(f"  wrote {hpath}")
    print("  bake: gxtexconv -i steve.png  -o steve.tpl  colfmt=5 mipmap=no")
    print("        gxtexconv -i dragon.png -o dragon.tpl colfmt=5 mipmap=no")


if __name__ == "__main__":
    main()
