/* Generated by tools/build_atlas.py -- do not edit. */
#ifndef MSW_ATLAS_GEN_H
#define MSW_ATLAS_GEN_H

#define ATLAS_TILE 16
#define ATLAS_PAD 8
#define ATLAS_CELL 32
#define ATLAS_COLS 32
#define ATLAS_TEX_W 1024
#define ATLAS_TEX_H 1024
#define ATLAS_MAXLOD 2

#endif
