/* Generated by tools/gen_blockmap.py -- do not edit. */
#ifndef MSW_BLOCKMAP_GEN_H
#define MSW_BLOCKMAP_GEN_H

/* FNV-1a/32 over data/blockids.txt. Sent in the GCLink HELLO
 * both ways: the console's baked-in atlas/shape/props tables and
 * the proxy's blockmap.json are only interchangeable if this
 * matches, so a stale blockmap must fail the handshake rather
 * than render a whole map as the wrong blocks. */
#define BLOCKMAP_HASH 0x7C8C4186u

/* Last palette entry: the placeholder a 1.8 block state with no
 * global id resolves to. World_SetBlock clamps out-of-range ids
 * here -- world.c indexes g_blockShape[]/g_topTile[] by global id
 * with no bounds check of its own, so an id past the palette would
 * otherwise read off the end of those tables. */
#define BLOCKMAP_SENTINEL_ID 568

#endif
