/* Generated by tools/build_atlas.py -- do not edit. */
#ifndef MSW_BLOCK_BOOK_GEN_H
#define MSW_BLOCK_BOOK_GEN_H

/* Extra atlas tiles that block_shapes.c's mesh emitters need by
 * index (not part of the per-global-id side/top/bottom tables). */

/* Enchanting table's static floating book (mesh_enchant_table):
 * leather cover on its two flat faces, page edges on its sides. */
#define ENCHANT_BOOK_COVER_TILE 666
#define ENCHANT_BOOK_PAGES_TILE 667

/* Anvil working-surface texture for the top box's up-face only
 * (mesh_anvil); all other anvil faces use anvil_base. */
#define ANVIL_TOP_TILE 668

/* Default Steve head tiles for skulls (mesh_skull): front face
 * on the 4 sides, plus the head's top and bottom. */
#define SKULL_SIDE_TILE 669
#define SKULL_TOP_TILE 670
#define SKULL_BOTTOM_TILE 671

/* Held/dropped ITEMS (not placeable blocks): the atlas tile
 * index is used directly as the inventory ItemStack.item id.
 * Being >= NUM_BLOCK_IDS is how helditem.c distinguishes a
 * flat item from a block. See source/items.h for the tools'
 * dig properties and block_props_gen.h for the drop tables. */
#define ITEM_DIAMOND_SWORD_TILE 672
#define ITEM_DIAMOND_PICKAXE_TILE 673
#define ITEM_DIAMOND_AXE_TILE 674
#define ITEM_DIAMOND_SHOVEL_TILE 675
#define ITEM_COAL_TILE 676
#define ITEM_DIAMOND_TILE 677
#define ITEM_REDSTONE_TILE 678
#define ITEM_QUARTZ_TILE 679
#define ITEM_FLINT_TILE 680
#define ITEM_CLAY_BALL_TILE 681
#define ITEM_STRING_TILE 682
#define ITEM_SNOWBALL_TILE 683
#define ITEM_WHEAT_TILE 684
#define ITEM_WHEAT_SEEDS_TILE 685
#define ITEM_BOOK_TILE 686
#define ITEM_SIGN_TILE 687
#define ITEM_DOOR_WOOD_TILE 688
#define ITEM_BED_TILE 689
#define ITEM_COCOA_BEANS_TILE 690
#define ITEM_NETHER_WART_TILE 691
#define ITEM_BOW_TILE 692
#define ITEM_ARROW_TILE 693
#define ITEM_FISHING_ROD_TILE 694
#define ITEM_GOLDEN_APPLE_TILE 695
#define ITEM_WATER_BUCKET_TILE 696
#define ITEM_LAVA_BUCKET_TILE 697
#define ITEM_ENDER_PEARL_TILE 698
#define ITEM_DIAMOND_HELMET_TILE 699
#define ITEM_DIAMOND_CHESTPLATE_TILE 700
#define ITEM_DIAMOND_LEGGINGS_TILE 701
#define ITEM_DIAMOND_BOOTS_TILE 702

/* Potions, one finished tile per effect: the bottle with the
 * liquid already tinted in (see potion_tex). The proxy keys
 * these on the stack's damage value, not its item id. */
#define ITEM_SPLASH_SPEED_TILE 703
#define ITEM_SPLASH_REGEN_TILE 704
#define ITEM_FIRE_RESISTANCE_POTION_TILE 705

/* Block-breaking crack overlay: DESTROY_STAGE_TILE + stage,
 * stage in 0..DESTROY_STAGE_COUNT-1 (vanilla destroy_stage_N). */
#define DESTROY_STAGE_TILE 706
#define DESTROY_STAGE_COUNT 10

/* Total tiles packed into the atlas (block tiles + face
 * overrides + the extras above); an id/tile past this is a bug. */
#define NUM_ATLAS_TILES 716

#endif
