/* Generated by tools/gen_block_props.py -- do not edit. */
#ifndef MSW_BLOCK_PROPS_GEN_H
#define MSW_BLOCK_PROPS_GEN_H

#include "block_faces_gen.h"   /* NUM_BLOCK_IDS */
#include "block_book_gen.h"    /* ITEM_*_TILE drop ids */

/* Material, reduced to the distinctions Minecraft 1.8.9's dig-speed
 * and drop rules actually make (see ItemPickaxe/ItemAxe/ItemSpade/
 * ItemSword.getStrVsBlock and Material.setRequiresTool). */
enum {
	MAT_AIR = 0,
	MAT_ROCK = 1,
	MAT_IRON = 2,
	MAT_ANVIL = 3,
	MAT_WOOD = 4,
	MAT_PLANTS = 5,
	MAT_VINE = 6,
	MAT_LEAVES = 7,
	MAT_GOURD = 8,
	MAT_GROUND = 9,
	MAT_GRASS = 10,
	MAT_SAND = 11,
	MAT_CLAY = 12,
	MAT_SNOW = 13,
	MAT_CRAFTED_SNOW = 14,
	MAT_CLOTH = 15,
	MAT_CARPET = 16,
	MAT_GLASS = 17,
	MAT_ICE = 18,
	MAT_WEB = 19,
	MAT_CIRCUITS = 20,
	MAT_WATER = 21,
	MAT_FIRE = 22,
	MAT_PISTON = 23,
	MAT_CAKE = 24,
	MAT_LAVA = 25,
};

/* Tool classes (Item subclasses that override getStrVsBlock). */
enum {
	TOOL_NONE = 0,
	TOOL_PICKAXE = 1,
	TOOL_AXE = 2,
	TOOL_SHOVEL = 3,
	TOOL_SWORD = 4,
};

/* How ItemBlock.onItemUse derives the placed block's data value
 * from the click (Block.onBlockPlaced); see interact.c. */
enum {
	PLACE_PLAIN = 0,
	PLACE_STAIR = 1,
	PLACE_SLAB = 2,
	PLACE_PILLAR = 3,
	PLACE_TORCH = 4,
	PLACE_HFACING = 5,
	PLACE_LADDER = 6,
	PLACE_GATE = 7,
	PLACE_ANVIL = 8,
};

typedef struct {
	float hardness;   /* Block.blockHardness; < 0 = unbreakable   */
	s16   drop;       /* dropped id (block id or item tile), -1 = none */
	s16   dropAlt;    /* drop when the 1-in-dropDenom roll fails   */
	u8    material;   /* MAT_*                                     */
	u8    speedTool;  /* TOOL_* that gets its efficiency bonus here */
	u8    harvestTool;/* TOOL_* required to drop (TOOL_NONE = hands)*/
	u8    harvestLevel;/* tool material tier required (0 wood..3 diamond) */
	u8    dropMin, dropMax;  /* quantityDropped() range, inclusive  */
	u8    dropDenom;  /* 1 = always; N = 1-in-N chance, else dropAlt */
	u8    replaceable;/* Material.isReplaceable(): a placed block
	                   * overwrites this instead of sitting on it */
	u16   family;     /* index into g_blockVariant[]                */
	u8    data;       /* this id's vanilla metadata value           */
} BlockProps;

static const BlockProps g_blockProps[NUM_BLOCK_IDS] = {
	{ 2.00f, 0, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 0, 0 },  /* 0 ACACIA_FENCE */
	{ 2.00f, 1, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 1, 0 },  /* 1 ACACIA_STAIRS */
	{ 2.00f, 2, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 1, 1 },  /* 2 ACACIA_STAIRS:1 */
	{ 2.00f, 3, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 1, 2 },  /* 3 ACACIA_STAIRS:2 */
	{ 2.00f, 4, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 1, 3 },  /* 4 ACACIA_STAIRS:3 */
	{ 2.00f, 5, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 1, 4 },  /* 5 ACACIA_STAIRS:4 */
	{ 2.00f, 6, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 1, 5 },  /* 6 ACACIA_STAIRS:5 */
	{ 2.00f, 7, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 1, 6 },  /* 7 ACACIA_STAIRS:6 */
	{ 2.00f, 8, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 1, 7 },  /* 8 ACACIA_STAIRS:7 */
	{ 5.00f, 9, -1, MAT_ANVIL, 1, 1, 0, 1, 1, 1, 0, 2, 0 },  /* 9 ANVIL */
	{ 5.00f, 10, -1, MAT_ANVIL, 1, 1, 0, 1, 1, 1, 0, 2, 1 },  /* 10 ANVIL:1 */
	{ 5.00f, 11, -1, MAT_ANVIL, 1, 1, 0, 1, 1, 1, 0, 2, 2 },  /* 11 ANVIL:2 */
	{ 5.00f, 12, -1, MAT_ANVIL, 1, 1, 0, 1, 1, 1, 0, 2, 3 },  /* 12 ANVIL:3 */
	{ 5.00f, 13, -1, MAT_ANVIL, 1, 1, 0, 1, 1, 1, 0, 2, 5 },  /* 13 ANVIL:5 */
	{ 5.00f, 14, -1, MAT_ANVIL, 1, 1, 0, 1, 1, 1, 0, 2, 7 },  /* 14 ANVIL:7 */
	{ 5.00f, 15, -1, MAT_ANVIL, 1, 1, 0, 1, 1, 1, 0, 2, 9 },  /* 15 ANVIL:9 */
	{ -1.00f, -1, -1, MAT_ROCK, 1, 1, 0, 0, 0, 1, 0, 3, 0 },  /* 16 BEDROCK */
	{ 0.20f, ITEM_BED_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 4, 1 },  /* 17 BED_BLOCK:1 */
	{ 2.00f, 18, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 5, 0 },  /* 18 BIRCH_FENCE */
	{ 2.00f, 19, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 6, 1 },  /* 19 BIRCH_FENCE_GATE:1 */
	{ 2.00f, 20, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 6, 2 },  /* 20 BIRCH_FENCE_GATE:2 */
	{ 2.00f, 21, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 6, 3 },  /* 21 BIRCH_FENCE_GATE:3 */
	{ 2.00f, 22, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 6, 4 },  /* 22 BIRCH_FENCE_GATE:4 */
	{ 2.00f, 23, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 7, 0 },  /* 23 BIRCH_WOOD_STAIRS */
	{ 2.00f, 24, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 7, 1 },  /* 24 BIRCH_WOOD_STAIRS:1 */
	{ 2.00f, 25, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 7, 2 },  /* 25 BIRCH_WOOD_STAIRS:2 */
	{ 2.00f, 26, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 7, 3 },  /* 26 BIRCH_WOOD_STAIRS:3 */
	{ 2.00f, 27, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 7, 4 },  /* 27 BIRCH_WOOD_STAIRS:4 */
	{ 2.00f, 28, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 7, 5 },  /* 28 BIRCH_WOOD_STAIRS:5 */
	{ 2.00f, 29, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 7, 6 },  /* 29 BIRCH_WOOD_STAIRS:6 */
	{ 2.00f, 30, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 7, 7 },  /* 30 BIRCH_WOOD_STAIRS:7 */
	{ 2.00f, ITEM_BOOK_TILE, -1, MAT_WOOD, 2, 0, 0, 3, 3, 1, 0, 8, 0 },  /* 31 BOOKSHELF */
	{ 0.50f, 32, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 9, 0 },  /* 32 BREWING_STAND */
	{ 2.00f, 33, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 10, 0 },  /* 33 BRICK */
	{ 2.00f, 34, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 11, 0 },  /* 34 BRICK_STAIRS */
	{ 2.00f, 35, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 11, 1 },  /* 35 BRICK_STAIRS:1 */
	{ 2.00f, 36, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 11, 2 },  /* 36 BRICK_STAIRS:2 */
	{ 2.00f, 37, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 11, 3 },  /* 37 BRICK_STAIRS:3 */
	{ 2.00f, 38, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 11, 4 },  /* 38 BRICK_STAIRS:4 */
	{ 2.00f, 39, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 11, 5 },  /* 39 BRICK_STAIRS:5 */
	{ 2.00f, 40, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 11, 6 },  /* 40 BRICK_STAIRS:6 */
	{ 2.00f, 41, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 11, 7 },  /* 41 BRICK_STAIRS:7 */
	{ 0.00f, 42, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 12, 0 },  /* 42 BROWN_MUSHROOM */
	{ 0.10f, 43, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 0 },  /* 43 CARPET */
	{ 0.10f, 44, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 1 },  /* 44 CARPET:1 */
	{ 0.10f, 45, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 11 },  /* 45 CARPET:11 */
	{ 0.10f, 46, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 12 },  /* 46 CARPET:12 */
	{ 0.10f, 47, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 13 },  /* 47 CARPET:13 */
	{ 0.10f, 48, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 14 },  /* 48 CARPET:14 */
	{ 0.10f, 49, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 3 },  /* 49 CARPET:3 */
	{ 0.10f, 50, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 8 },  /* 50 CARPET:8 */
	{ 0.10f, 51, -1, MAT_CARPET, 0, 0, 0, 1, 1, 1, 0, 13, 9 },  /* 51 CARPET:9 */
	{ 2.00f, 52, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 14, 0 },  /* 52 CAULDRON */
	{ 2.00f, 53, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 14, 3 },  /* 53 CAULDRON:3 */
	{ 2.50f, 54, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 15, 2 },  /* 54 CHEST:2 */
	{ 2.50f, 55, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 15, 3 },  /* 55 CHEST:3 */
	{ 2.50f, 56, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 15, 4 },  /* 56 CHEST:4 */
	{ 2.50f, 57, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 15, 5 },  /* 57 CHEST:5 */
	{ 0.60f, ITEM_CLAY_BALL_TILE, -1, MAT_CLAY, 3, 0, 0, 4, 4, 1, 0, 16, 0 },  /* 58 CLAY */
	{ 5.00f, 59, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 17, 0 },  /* 59 COAL_BLOCK */
	{ 3.00f, ITEM_COAL_TILE, -1, MAT_ROCK, 1, 1, 1, 1, 1, 1, 0, 18, 0 },  /* 60 COAL_ORE */
	{ 2.00f, 61, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 19, 0 },  /* 61 COBBLESTONE */
	{ 2.00f, 62, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 20, 0 },  /* 62 COBBLESTONE_STAIRS */
	{ 2.00f, 63, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 20, 1 },  /* 63 COBBLESTONE_STAIRS:1 */
	{ 2.00f, 64, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 20, 2 },  /* 64 COBBLESTONE_STAIRS:2 */
	{ 2.00f, 65, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 20, 3 },  /* 65 COBBLESTONE_STAIRS:3 */
	{ 2.00f, 66, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 20, 4 },  /* 66 COBBLESTONE_STAIRS:4 */
	{ 2.00f, 67, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 20, 5 },  /* 67 COBBLESTONE_STAIRS:5 */
	{ 2.00f, 68, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 20, 6 },  /* 68 COBBLESTONE_STAIRS:6 */
	{ 2.00f, 69, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 20, 7 },  /* 69 COBBLESTONE_STAIRS:7 */
	{ 2.00f, 70, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 21, 0 },  /* 70 COBBLE_WALL */
	{ 2.00f, 71, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 21, 1 },  /* 71 COBBLE_WALL:1 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 22, 0 },  /* 72 COCOA */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 22, 1 },  /* 73 COCOA:1 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 3, 3, 1, 0, 22, 10 },  /* 74 COCOA:10 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 3, 3, 1, 0, 22, 11 },  /* 75 COCOA:11 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 22, 2 },  /* 76 COCOA:2 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 22, 3 },  /* 77 COCOA:3 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 22, 4 },  /* 78 COCOA:4 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 22, 5 },  /* 79 COCOA:5 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 22, 6 },  /* 80 COCOA:6 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 22, 7 },  /* 81 COCOA:7 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 3, 3, 1, 0, 22, 8 },  /* 82 COCOA:8 */
	{ 0.20f, ITEM_COCOA_BEANS_TILE, -1, MAT_PLANTS, 2, 0, 0, 3, 3, 1, 0, 22, 9 },  /* 83 COCOA:9 */
	{ 0.00f, ITEM_WHEAT_SEEDS_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 23, 7 },  /* 84 CROPS:7 */
	{ 2.00f, 85, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 24, 0 },  /* 85 DARK_OAK_FENCE */
	{ 2.00f, 86, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 25, 0 },  /* 86 DARK_OAK_FENCE_GATE */
	{ 2.00f, 87, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 25, 1 },  /* 87 DARK_OAK_FENCE_GATE:1 */
	{ 2.00f, 88, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 25, 2 },  /* 88 DARK_OAK_FENCE_GATE:2 */
	{ 2.00f, 89, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 25, 3 },  /* 89 DARK_OAK_FENCE_GATE:3 */
	{ 2.00f, 90, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 25, 4 },  /* 90 DARK_OAK_FENCE_GATE:4 */
	{ 2.00f, 91, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 25, 5 },  /* 91 DARK_OAK_FENCE_GATE:5 */
	{ 2.00f, 92, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 25, 6 },  /* 92 DARK_OAK_FENCE_GATE:6 */
	{ 2.00f, 93, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 25, 7 },  /* 93 DARK_OAK_FENCE_GATE:7 */
	{ 2.00f, 94, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 26, 0 },  /* 94 DARK_OAK_STAIRS */
	{ 2.00f, 95, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 26, 1 },  /* 95 DARK_OAK_STAIRS:1 */
	{ 2.00f, 96, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 26, 2 },  /* 96 DARK_OAK_STAIRS:2 */
	{ 2.00f, 97, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 26, 3 },  /* 97 DARK_OAK_STAIRS:3 */
	{ 2.00f, 98, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 26, 4 },  /* 98 DARK_OAK_STAIRS:4 */
	{ 2.00f, 99, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 26, 5 },  /* 99 DARK_OAK_STAIRS:5 */
	{ 2.00f, 100, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 26, 6 },  /* 100 DARK_OAK_STAIRS:6 */
	{ 2.00f, 101, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 26, 7 },  /* 101 DARK_OAK_STAIRS:7 */
	{ 0.00f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 27, 0 },  /* 102 DEAD_BUSH */
	{ 5.00f, 103, -1, MAT_IRON, 1, 1, 2, 1, 1, 1, 0, 28, 0 },  /* 103 DIAMOND_BLOCK */
	{ 3.00f, ITEM_DIAMOND_TILE, -1, MAT_ROCK, 1, 1, 2, 1, 1, 1, 0, 29, 0 },  /* 104 DIAMOND_ORE */
	{ 0.50f, 105, -1, MAT_GROUND, 3, 0, 0, 1, 1, 1, 0, 30, 0 },  /* 105 DIRT */
	{ 0.50f, 106, -1, MAT_GROUND, 3, 0, 0, 1, 1, 1, 0, 30, 1 },  /* 106 DIRT:1 */
	{ 0.50f, 107, -1, MAT_GROUND, 3, 0, 0, 1, 1, 1, 0, 30, 2 },  /* 107 DIRT:2 */
	{ 0.00f, 108, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 31, 10 },  /* 108 DOUBLE_PLANT:10 */
	{ 0.00f, 109, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 31, 3 },  /* 109 DOUBLE_PLANT:3 */
	{ 0.00f, 110, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 31, 4 },  /* 110 DOUBLE_PLANT:4 */
	{ 2.00f, 398, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 0 },  /* 111 DOUBLE_STEP */
	{ 2.00f, 399, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 1 },  /* 112 DOUBLE_STEP:1 */
	{ 2.00f, 400, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 11 },  /* 113 DOUBLE_STEP:11 */
	{ 2.00f, 401, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 13 },  /* 114 DOUBLE_STEP:13 */
	{ 2.00f, 404, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 3 },  /* 115 DOUBLE_STEP:3 */
	{ 2.00f, 405, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 5 },  /* 116 DOUBLE_STEP:5 */
	{ 2.00f, 406, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 6 },  /* 117 DOUBLE_STEP:6 */
	{ 2.00f, 407, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 7 },  /* 118 DOUBLE_STEP:7 */
	{ 2.00f, 408, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 8 },  /* 119 DOUBLE_STEP:8 */
	{ 2.00f, 409, -1, MAT_ROCK, 1, 1, 0, 2, 2, 1, 0, 32, 9 },  /* 120 DOUBLE_STEP:9 */
	{ 3.50f, 121, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 33, 1 },  /* 121 DROPPER:1 */
	{ 3.50f, 122, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 33, 13 },  /* 122 DROPPER:13 */
	{ 5.00f, 123, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 34, 0 },  /* 123 ENCHANTMENT_TABLE */
	{ 2.00f, 124, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 35, 0 },  /* 124 FENCE */
	{ 2.00f, 125, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 36, 1 },  /* 125 FENCE_GATE:1 */
	{ 2.00f, 126, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 36, 2 },  /* 126 FENCE_GATE:2 */
	{ 0.00f, -1, -1, MAT_FIRE, 0, 0, 0, 0, 0, 1, 1, 37, 15 },  /* 127 FIRE:15 */
	{ 3.50f, 128, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 38, 2 },  /* 128 FURNACE:2 */
	{ 3.50f, 129, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 38, 3 },  /* 129 FURNACE:3 */
	{ 3.50f, 130, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 38, 4 },  /* 130 FURNACE:4 */
	{ 3.50f, 131, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 38, 5 },  /* 131 FURNACE:5 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 39, 0 },  /* 132 GLASS */
	{ 0.30f, 133, -1, MAT_GLASS, 1, 0, 0, 1, 1, 1, 0, 40, 0 },  /* 133 GLOWSTONE */
	{ 3.00f, 134, -1, MAT_IRON, 1, 1, 2, 1, 1, 1, 0, 41, 0 },  /* 134 GOLD_BLOCK */
	{ 3.00f, 135, -1, MAT_ROCK, 1, 1, 2, 1, 1, 1, 0, 42, 0 },  /* 135 GOLD_ORE */
	{ 0.60f, 105, -1, MAT_GRASS, 3, 0, 0, 1, 1, 1, 0, 43, 0 },  /* 136 GRASS */
	{ 0.60f, ITEM_FLINT_TILE, 137, MAT_GROUND, 3, 0, 0, 1, 1, 10, 0, 44, 0 },  /* 137 GRAVEL */
	{ 1.25f, 138, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 45, 0 },  /* 138 HARD_CLAY */
	{ 0.50f, 139, -1, MAT_GRASS, 3, 0, 0, 1, 1, 1, 0, 46, 0 },  /* 139 HAY_BLOCK */
	{ 3.00f, 140, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 47, 0 },  /* 140 HOPPER */
	{ 3.00f, 141, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 47, 2 },  /* 141 HOPPER:2 */
	{ 3.00f, 142, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 47, 3 },  /* 142 HOPPER:3 */
	{ 3.00f, 143, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 47, 4 },  /* 143 HOPPER:4 */
	{ 3.00f, 144, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 47, 5 },  /* 144 HOPPER:5 */
	{ 0.20f, 42, -1, MAT_WOOD, 2, 0, 0, 0, 2, 1, 0, 48, 10 },  /* 145 HUGE_MUSHROOM_1:10 */
	{ 0.20f, 42, -1, MAT_WOOD, 2, 0, 0, 0, 2, 1, 0, 48, 14 },  /* 146 HUGE_MUSHROOM_1:14 */
	{ 0.20f, 270, -1, MAT_WOOD, 2, 0, 0, 0, 2, 1, 0, 49, 14 },  /* 147 HUGE_MUSHROOM_2:14 */
	{ 0.20f, 270, -1, MAT_WOOD, 2, 0, 0, 0, 2, 1, 0, 49, 15 },  /* 148 HUGE_MUSHROOM_2:15 */
	{ 0.50f, -1, -1, MAT_ICE, 1, 0, 0, 0, 0, 1, 0, 50, 0 },  /* 149 ICE */
	{ 5.00f, 150, -1, MAT_IRON, 1, 1, 1, 1, 1, 1, 0, 51, 0 },  /* 150 IRON_BLOCK */
	{ 5.00f, 151, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 52, 0 },  /* 151 IRON_FENCE */
	{ 3.00f, 152, -1, MAT_ROCK, 1, 1, 1, 1, 1, 1, 0, 53, 0 },  /* 152 IRON_ORE */
	{ 5.00f, 153, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 54, 0 },  /* 153 IRON_TRAPDOOR */
	{ 5.00f, 154, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 54, 1 },  /* 154 IRON_TRAPDOOR:1 */
	{ 5.00f, 155, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 54, 12 },  /* 155 IRON_TRAPDOOR:12 */
	{ 5.00f, 156, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 54, 13 },  /* 156 IRON_TRAPDOOR:13 */
	{ 5.00f, 157, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 54, 2 },  /* 157 IRON_TRAPDOOR:2 */
	{ 5.00f, 158, -1, MAT_IRON, 1, 1, 0, 1, 1, 1, 0, 54, 3 },  /* 158 IRON_TRAPDOOR:3 */
	{ 2.00f, 159, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 55, 0 },  /* 159 JUKEBOX */
	{ 3.00f, ITEM_DOOR_WOOD_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 56, 9 },  /* 160 JUNGLE_DOOR:9 */
	{ 2.00f, 161, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 57, 0 },  /* 161 JUNGLE_FENCE */
	{ 2.00f, 162, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 58, 0 },  /* 162 JUNGLE_WOOD_STAIRS */
	{ 2.00f, 163, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 58, 1 },  /* 163 JUNGLE_WOOD_STAIRS:1 */
	{ 2.00f, 164, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 58, 2 },  /* 164 JUNGLE_WOOD_STAIRS:2 */
	{ 2.00f, 165, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 58, 3 },  /* 165 JUNGLE_WOOD_STAIRS:3 */
	{ 2.00f, 166, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 58, 4 },  /* 166 JUNGLE_WOOD_STAIRS:4 */
	{ 2.00f, 167, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 58, 5 },  /* 167 JUNGLE_WOOD_STAIRS:5 */
	{ 2.00f, 168, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 58, 6 },  /* 168 JUNGLE_WOOD_STAIRS:6 */
	{ 2.00f, 169, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 58, 7 },  /* 169 JUNGLE_WOOD_STAIRS:7 */
	{ 0.40f, 170, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 59, 2 },  /* 170 LADDER:2 */
	{ 0.40f, 171, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 59, 3 },  /* 171 LADDER:3 */
	{ 0.40f, 172, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 59, 4 },  /* 172 LADDER:4 */
	{ 0.40f, 173, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 59, 5 },  /* 173 LADDER:5 */
	{ 3.00f, 174, -1, MAT_IRON, 1, 1, 1, 1, 1, 1, 0, 60, 0 },  /* 174 LAPIS_BLOCK */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 0 },  /* 175 LEAVES */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 11 },  /* 176 LEAVES:11 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 12 },  /* 177 LEAVES:12 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 13 },  /* 178 LEAVES:13 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 14 },  /* 179 LEAVES:14 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 15 },  /* 180 LEAVES:15 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 3 },  /* 181 LEAVES:3 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 4 },  /* 182 LEAVES:4 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 5 },  /* 183 LEAVES:5 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 6 },  /* 184 LEAVES:6 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 7 },  /* 185 LEAVES:7 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 61, 8 },  /* 186 LEAVES:8 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 62, 13 },  /* 187 LEAVES_2:13 */
	{ 0.20f, -1, -1, MAT_LEAVES, 0, 0, 0, 0, 0, 1, 0, 62, 5 },  /* 188 LEAVES_2:5 */
	{ 0.00f, 189, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 63, 10 },  /* 189 LEVER:10 */
	{ 0.00f, 190, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 63, 12 },  /* 190 LEVER:12 */
	{ 0.00f, 191, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 63, 13 },  /* 191 LEVER:13 */
	{ 0.00f, 192, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 63, 14 },  /* 192 LEVER:14 */
	{ 0.00f, 193, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 63, 15 },  /* 193 LEVER:15 */
	{ 0.00f, 194, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 63, 6 },  /* 194 LEVER:6 */
	{ 2.00f, 195, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 0 },  /* 195 LOG */
	{ 2.00f, 196, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 1 },  /* 196 LOG:1 */
	{ 2.00f, 197, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 11 },  /* 197 LOG:11 */
	{ 2.00f, 198, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 12 },  /* 198 LOG:12 */
	{ 2.00f, 199, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 13 },  /* 199 LOG:13 */
	{ 2.00f, 200, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 15 },  /* 200 LOG:15 */
	{ 2.00f, 201, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 3 },  /* 201 LOG:3 */
	{ 2.00f, 202, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 4 },  /* 202 LOG:4 */
	{ 2.00f, 203, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 5 },  /* 203 LOG:5 */
	{ 2.00f, 204, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 7 },  /* 204 LOG:7 */
	{ 2.00f, 205, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 8 },  /* 205 LOG:8 */
	{ 2.00f, 206, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 64, 9 },  /* 206 LOG:9 */
	{ 2.00f, 207, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 65, 0 },  /* 207 LOG_2 */
	{ 2.00f, 208, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 65, 1 },  /* 208 LOG_2:1 */
	{ 2.00f, 209, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 65, 12 },  /* 209 LOG_2:12 */
	{ 2.00f, 210, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 65, 13 },  /* 210 LOG_2:13 */
	{ 2.00f, 211, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 65, 4 },  /* 211 LOG_2:4 */
	{ 2.00f, 212, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 65, 5 },  /* 212 LOG_2:5 */
	{ 2.00f, 213, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 65, 8 },  /* 213 LOG_2:8 */
	{ 2.00f, 214, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 65, 9 },  /* 214 LOG_2:9 */
	{ 0.00f, ITEM_WHEAT_SEEDS_TILE, -1, MAT_VINE, 2, 0, 0, 1, 1, 8, 1, 66, 1 },  /* 215 LONG_GRASS:1 */
	{ 0.00f, ITEM_WHEAT_SEEDS_TILE, -1, MAT_VINE, 2, 0, 0, 1, 1, 8, 1, 66, 2 },  /* 216 LONG_GRASS:2 */
	{ 0.75f, -1, -1, MAT_ROCK, 1, 1, 0, 0, 0, 1, 0, 67, 0 },  /* 217 MONSTER_EGGS */
	{ 0.75f, -1, -1, MAT_ROCK, 1, 1, 0, 0, 0, 1, 0, 67, 2 },  /* 218 MONSTER_EGGS:2 */
	{ 2.00f, 219, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 68, 0 },  /* 219 MOSSY_COBBLESTONE */
	{ 0.60f, 105, -1, MAT_GRASS, 3, 0, 0, 1, 1, 1, 0, 69, 0 },  /* 220 MYCEL */
	{ 0.40f, 221, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 70, 0 },  /* 221 NETHERRACK */
	{ 2.00f, 222, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 71, 0 },  /* 222 NETHER_BRICK */
	{ 2.00f, 223, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 72, 0 },  /* 223 NETHER_BRICK_STAIRS */
	{ 2.00f, 224, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 72, 1 },  /* 224 NETHER_BRICK_STAIRS:1 */
	{ 2.00f, 225, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 72, 2 },  /* 225 NETHER_BRICK_STAIRS:2 */
	{ 2.00f, 226, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 72, 3 },  /* 226 NETHER_BRICK_STAIRS:3 */
	{ 2.00f, 227, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 72, 4 },  /* 227 NETHER_BRICK_STAIRS:4 */
	{ 2.00f, 228, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 72, 5 },  /* 228 NETHER_BRICK_STAIRS:5 */
	{ 2.00f, 229, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 72, 6 },  /* 229 NETHER_BRICK_STAIRS:6 */
	{ 2.00f, 230, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 72, 7 },  /* 230 NETHER_BRICK_STAIRS:7 */
	{ 2.00f, 231, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 73, 0 },  /* 231 NETHER_FENCE */
	{ 0.00f, ITEM_NETHER_WART_TILE, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 74, 3 },  /* 232 NETHER_WARTS:3 */
	{ 0.80f, 233, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 75, 0 },  /* 233 NOTE_BLOCK */
	{ 50.00f, 234, -1, MAT_ROCK, 1, 1, 3, 1, 1, 1, 0, 76, 0 },  /* 234 OBSIDIAN */
	{ 0.50f, -1, -1, MAT_ICE, 1, 0, 0, 0, 0, 1, 0, 77, 0 },  /* 235 PACKED_ICE */
	{ 0.50f, 236, -1, MAT_PISTON, 1, 0, 0, 1, 1, 1, 0, 78, 1 },  /* 236 PISTON_BASE:1 */
	{ 0.70f, 237, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 10 },  /* 237 POWERED_RAIL:10 */
	{ 0.70f, 238, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 11 },  /* 238 POWERED_RAIL:11 */
	{ 0.70f, 239, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 12 },  /* 239 POWERED_RAIL:12 */
	{ 0.70f, 240, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 13 },  /* 240 POWERED_RAIL:13 */
	{ 0.70f, 241, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 2 },  /* 241 POWERED_RAIL:2 */
	{ 0.70f, 242, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 3 },  /* 242 POWERED_RAIL:3 */
	{ 0.70f, 243, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 4 },  /* 243 POWERED_RAIL:4 */
	{ 0.70f, 244, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 5 },  /* 244 POWERED_RAIL:5 */
	{ 0.70f, 245, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 8 },  /* 245 POWERED_RAIL:8 */
	{ 0.70f, 246, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 79, 9 },  /* 246 POWERED_RAIL:9 */
	{ 1.50f, 247, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 80, 0 },  /* 247 PRISMARINE */
	{ 1.50f, 248, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 80, 2 },  /* 248 PRISMARINE:2 */
	{ 0.80f, 249, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 81, 0 },  /* 249 QUARTZ_BLOCK */
	{ 0.80f, 250, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 81, 1 },  /* 250 QUARTZ_BLOCK:1 */
	{ 0.80f, 251, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 81, 2 },  /* 251 QUARTZ_BLOCK:2 */
	{ 0.80f, 252, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 81, 3 },  /* 252 QUARTZ_BLOCK:3 */
	{ 0.80f, 253, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 81, 4 },  /* 253 QUARTZ_BLOCK:4 */
	{ 3.00f, ITEM_QUARTZ_TILE, -1, MAT_ROCK, 1, 1, 1, 1, 1, 1, 0, 82, 0 },  /* 254 QUARTZ_ORE */
	{ 0.80f, 255, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 83, 0 },  /* 255 QUARTZ_STAIRS */
	{ 0.80f, 256, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 83, 1 },  /* 256 QUARTZ_STAIRS:1 */
	{ 0.80f, 257, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 83, 2 },  /* 257 QUARTZ_STAIRS:2 */
	{ 0.80f, 258, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 83, 3 },  /* 258 QUARTZ_STAIRS:3 */
	{ 0.80f, 259, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 83, 4 },  /* 259 QUARTZ_STAIRS:4 */
	{ 0.80f, 260, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 83, 5 },  /* 260 QUARTZ_STAIRS:5 */
	{ 0.80f, 261, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 83, 6 },  /* 261 QUARTZ_STAIRS:6 */
	{ 0.80f, 262, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 83, 7 },  /* 262 QUARTZ_STAIRS:7 */
	{ 0.70f, 263, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 84, 6 },  /* 263 RAILS:6 */
	{ 0.70f, 264, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 84, 7 },  /* 264 RAILS:7 */
	{ 0.70f, 265, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 84, 8 },  /* 265 RAILS:8 */
	{ 0.70f, 266, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 84, 9 },  /* 266 RAILS:9 */
	{ 5.00f, 267, -1, MAT_IRON, 1, 1, 2, 1, 1, 1, 0, 85, 0 },  /* 267 REDSTONE_BLOCK */
	{ 0.30f, 268, -1, MAT_GLASS, 1, 0, 0, 1, 1, 1, 0, 86, 0 },  /* 268 REDSTONE_LAMP_ON */
	{ 0.00f, ITEM_REDSTONE_TILE, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 87, 0 },  /* 269 REDSTONE_WIRE */
	{ 0.00f, 270, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 88, 0 },  /* 270 RED_MUSHROOM */
	{ 0.00f, 271, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 89, 0 },  /* 271 RED_ROSE */
	{ 0.00f, 272, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 89, 1 },  /* 272 RED_ROSE:1 */
	{ 0.00f, 273, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 89, 2 },  /* 273 RED_ROSE:2 */
	{ 0.00f, 274, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 89, 3 },  /* 274 RED_ROSE:3 */
	{ 0.00f, 275, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 89, 7 },  /* 275 RED_ROSE:7 */
	{ 0.80f, 276, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 90, 0 },  /* 276 RED_SANDSTONE */
	{ 0.80f, 277, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 90, 1 },  /* 277 RED_SANDSTONE:1 */
	{ 0.80f, 278, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 90, 2 },  /* 278 RED_SANDSTONE:2 */
	{ 0.80f, 279, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 91, 6 },  /* 279 RED_SANDSTONE_STAIRS:6 */
	{ 0.80f, 280, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 91, 7 },  /* 280 RED_SANDSTONE_STAIRS:7 */
	{ 0.50f, 281, -1, MAT_SAND, 3, 0, 0, 1, 1, 1, 0, 92, 0 },  /* 281 SAND */
	{ 0.50f, 282, -1, MAT_SAND, 3, 0, 0, 1, 1, 1, 0, 92, 1 },  /* 282 SAND:1 */
	{ 0.80f, 283, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 93, 0 },  /* 283 SANDSTONE */
	{ 0.80f, 284, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 93, 1 },  /* 284 SANDSTONE:1 */
	{ 0.80f, 285, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 93, 2 },  /* 285 SANDSTONE:2 */
	{ 0.80f, 286, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 94, 0 },  /* 286 SANDSTONE_STAIRS */
	{ 0.80f, 287, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 94, 1 },  /* 287 SANDSTONE_STAIRS:1 */
	{ 0.80f, 288, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 94, 2 },  /* 288 SANDSTONE_STAIRS:2 */
	{ 0.80f, 289, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 94, 3 },  /* 289 SANDSTONE_STAIRS:3 */
	{ 0.80f, 290, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 94, 4 },  /* 290 SANDSTONE_STAIRS:4 */
	{ 0.80f, 291, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 94, 5 },  /* 291 SANDSTONE_STAIRS:5 */
	{ 0.80f, 292, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 94, 6 },  /* 292 SANDSTONE_STAIRS:6 */
	{ 0.80f, 293, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 94, 7 },  /* 293 SANDSTONE_STAIRS:7 */
	{ 0.30f, 294, -1, MAT_GLASS, 1, 0, 0, 1, 1, 1, 0, 95, 0 },  /* 294 SEA_LANTERN */
	{ 1.00f, ITEM_SIGN_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 96, 12 },  /* 295 SIGN_POST:12 */
	{ 1.00f, 296, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 97, 1 },  /* 296 SKULL:1 */
	{ 1.00f, 297, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 97, 3 },  /* 297 SKULL:3 */
	{ 1.00f, 298, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 97, 4 },  /* 298 SKULL:4 */
	{ 1.00f, 299, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 97, 5 },  /* 299 SKULL:5 */
	{ 0.00f, 300, -1, MAT_CLAY, 3, 0, 0, 1, 1, 1, 0, 98, 0 },  /* 300 SLIME_BLOCK */
	{ 1.50f, 301, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 99, 0 },  /* 301 SMOOTH_BRICK */
	{ 1.50f, 302, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 99, 1 },  /* 302 SMOOTH_BRICK:1 */
	{ 1.50f, 303, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 99, 2 },  /* 303 SMOOTH_BRICK:2 */
	{ 1.50f, 304, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 99, 3 },  /* 304 SMOOTH_BRICK:3 */
	{ 1.50f, 305, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 100, 0 },  /* 305 SMOOTH_STAIRS */
	{ 1.50f, 306, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 100, 1 },  /* 306 SMOOTH_STAIRS:1 */
	{ 1.50f, 307, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 100, 2 },  /* 307 SMOOTH_STAIRS:2 */
	{ 1.50f, 308, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 100, 3 },  /* 308 SMOOTH_STAIRS:3 */
	{ 1.50f, 309, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 100, 4 },  /* 309 SMOOTH_STAIRS:4 */
	{ 1.50f, 310, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 100, 5 },  /* 310 SMOOTH_STAIRS:5 */
	{ 1.50f, 311, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 100, 6 },  /* 311 SMOOTH_STAIRS:6 */
	{ 1.50f, 312, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 100, 7 },  /* 312 SMOOTH_STAIRS:7 */
	{ 0.10f, ITEM_SNOWBALL_TILE, -1, MAT_SNOW, 3, 3, 0, 1, 1, 1, 1, 101, 0 },  /* 313 SNOW */
	{ 0.10f, ITEM_SNOWBALL_TILE, -1, MAT_SNOW, 3, 3, 0, 2, 2, 1, 1, 101, 1 },  /* 314 SNOW:1 */
	{ 0.10f, ITEM_SNOWBALL_TILE, -1, MAT_SNOW, 3, 3, 0, 3, 3, 1, 1, 101, 2 },  /* 315 SNOW:2 */
	{ 0.10f, ITEM_SNOWBALL_TILE, -1, MAT_SNOW, 3, 3, 0, 4, 4, 1, 1, 101, 3 },  /* 316 SNOW:3 */
	{ 0.10f, ITEM_SNOWBALL_TILE, -1, MAT_SNOW, 3, 3, 0, 5, 5, 1, 1, 101, 4 },  /* 317 SNOW:4 */
	{ 0.10f, ITEM_SNOWBALL_TILE, -1, MAT_SNOW, 3, 3, 0, 6, 6, 1, 1, 101, 5 },  /* 318 SNOW:5 */
	{ 0.10f, ITEM_SNOWBALL_TILE, -1, MAT_SNOW, 3, 3, 0, 7, 7, 1, 1, 101, 6 },  /* 319 SNOW:6 */
	{ 0.20f, ITEM_SNOWBALL_TILE, -1, MAT_CRAFTED_SNOW, 3, 3, 0, 4, 4, 1, 0, 102, 0 },  /* 320 SNOW_BLOCK */
	{ 0.50f, 105, -1, MAT_GROUND, 3, 0, 0, 1, 1, 1, 0, 103, 7 },  /* 321 SOIL:7 */
	{ 0.50f, 322, -1, MAT_SAND, 3, 0, 0, 1, 1, 1, 0, 104, 0 },  /* 322 SOUL_SAND */
	{ 0.50f, 323, -1, MAT_GRASS, 3, 0, 0, 1, 1, 1, 0, 105, 0 },  /* 323 SPONGE */
	{ 2.00f, 324, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 106, 0 },  /* 324 SPRUCE_FENCE */
	{ 2.00f, 325, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 107, 0 },  /* 325 SPRUCE_FENCE_GATE */
	{ 2.00f, 326, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 107, 1 },  /* 326 SPRUCE_FENCE_GATE:1 */
	{ 2.00f, 327, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 107, 2 },  /* 327 SPRUCE_FENCE_GATE:2 */
	{ 2.00f, 328, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 107, 3 },  /* 328 SPRUCE_FENCE_GATE:3 */
	{ 2.00f, 329, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 107, 6 },  /* 329 SPRUCE_FENCE_GATE:6 */
	{ 2.00f, 330, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 107, 7 },  /* 330 SPRUCE_FENCE_GATE:7 */
	{ 2.00f, 331, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 108, 0 },  /* 331 SPRUCE_WOOD_STAIRS */
	{ 2.00f, 332, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 108, 1 },  /* 332 SPRUCE_WOOD_STAIRS:1 */
	{ 2.00f, 333, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 108, 2 },  /* 333 SPRUCE_WOOD_STAIRS:2 */
	{ 2.00f, 334, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 108, 3 },  /* 334 SPRUCE_WOOD_STAIRS:3 */
	{ 2.00f, 335, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 108, 4 },  /* 335 SPRUCE_WOOD_STAIRS:4 */
	{ 2.00f, 336, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 108, 5 },  /* 336 SPRUCE_WOOD_STAIRS:5 */
	{ 2.00f, 337, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 108, 6 },  /* 337 SPRUCE_WOOD_STAIRS:6 */
	{ 2.00f, 338, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 108, 7 },  /* 338 SPRUCE_WOOD_STAIRS:7 */
	{ 1.25f, 339, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 0 },  /* 339 STAINED_CLAY */
	{ 1.25f, 340, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 1 },  /* 340 STAINED_CLAY:1 */
	{ 1.25f, 341, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 10 },  /* 341 STAINED_CLAY:10 */
	{ 1.25f, 342, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 11 },  /* 342 STAINED_CLAY:11 */
	{ 1.25f, 343, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 12 },  /* 343 STAINED_CLAY:12 */
	{ 1.25f, 344, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 13 },  /* 344 STAINED_CLAY:13 */
	{ 1.25f, 345, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 14 },  /* 345 STAINED_CLAY:14 */
	{ 1.25f, 346, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 15 },  /* 346 STAINED_CLAY:15 */
	{ 1.25f, 347, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 2 },  /* 347 STAINED_CLAY:2 */
	{ 1.25f, 348, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 3 },  /* 348 STAINED_CLAY:3 */
	{ 1.25f, 349, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 4 },  /* 349 STAINED_CLAY:4 */
	{ 1.25f, 350, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 5 },  /* 350 STAINED_CLAY:5 */
	{ 1.25f, 351, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 6 },  /* 351 STAINED_CLAY:6 */
	{ 1.25f, 352, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 7 },  /* 352 STAINED_CLAY:7 */
	{ 1.25f, 353, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 8 },  /* 353 STAINED_CLAY:8 */
	{ 1.25f, 354, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 109, 9 },  /* 354 STAINED_CLAY:9 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 0 },  /* 355 STAINED_GLASS */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 1 },  /* 356 STAINED_GLASS:1 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 10 },  /* 357 STAINED_GLASS:10 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 11 },  /* 358 STAINED_GLASS:11 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 13 },  /* 359 STAINED_GLASS:13 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 14 },  /* 360 STAINED_GLASS:14 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 15 },  /* 361 STAINED_GLASS:15 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 2 },  /* 362 STAINED_GLASS:2 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 3 },  /* 363 STAINED_GLASS:3 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 4 },  /* 364 STAINED_GLASS:4 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 5 },  /* 365 STAINED_GLASS:5 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 6 },  /* 366 STAINED_GLASS:6 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 8 },  /* 367 STAINED_GLASS:8 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 110, 9 },  /* 368 STAINED_GLASS:9 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 0 },  /* 369 STAINED_GLASS_PANE */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 1 },  /* 370 STAINED_GLASS_PANE:1 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 11 },  /* 371 STAINED_GLASS_PANE:11 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 13 },  /* 372 STAINED_GLASS_PANE:13 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 14 },  /* 373 STAINED_GLASS_PANE:14 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 15 },  /* 374 STAINED_GLASS_PANE:15 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 2 },  /* 375 STAINED_GLASS_PANE:2 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 3 },  /* 376 STAINED_GLASS_PANE:3 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 4 },  /* 377 STAINED_GLASS_PANE:4 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 5 },  /* 378 STAINED_GLASS_PANE:5 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 6 },  /* 379 STAINED_GLASS_PANE:6 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 7 },  /* 380 STAINED_GLASS_PANE:7 */
	{ 0.30f, -1, -1, MAT_GLASS, 1, 0, 0, 0, 0, 1, 0, 111, 8 },  /* 381 STAINED_GLASS_PANE:8 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 0 },  /* 382 STATIONARY_WATER */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 1 },  /* 383 STATIONARY_WATER:1 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 10 },  /* 384 STATIONARY_WATER:10 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 11 },  /* 385 STATIONARY_WATER:11 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 12 },  /* 386 STATIONARY_WATER:12 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 13 },  /* 387 STATIONARY_WATER:13 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 14 },  /* 388 STATIONARY_WATER:14 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 15 },  /* 389 STATIONARY_WATER:15 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 2 },  /* 390 STATIONARY_WATER:2 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 3 },  /* 391 STATIONARY_WATER:3 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 4 },  /* 392 STATIONARY_WATER:4 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 5 },  /* 393 STATIONARY_WATER:5 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 6 },  /* 394 STATIONARY_WATER:6 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 7 },  /* 395 STATIONARY_WATER:7 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 8 },  /* 396 STATIONARY_WATER:8 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 112, 9 },  /* 397 STATIONARY_WATER:9 */
	{ 2.00f, 398, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 0 },  /* 398 STEP */
	{ 2.00f, 399, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 1 },  /* 399 STEP:1 */
	{ 2.00f, 400, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 11 },  /* 400 STEP:11 */
	{ 2.00f, 401, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 13 },  /* 401 STEP:13 */
	{ 2.00f, 402, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 14 },  /* 402 STEP:14 */
	{ 2.00f, 403, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 15 },  /* 403 STEP:15 */
	{ 2.00f, 404, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 3 },  /* 404 STEP:3 */
	{ 2.00f, 405, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 5 },  /* 405 STEP:5 */
	{ 2.00f, 406, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 6 },  /* 406 STEP:6 */
	{ 2.00f, 407, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 7 },  /* 407 STEP:7 */
	{ 2.00f, 408, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 8 },  /* 408 STEP:8 */
	{ 2.00f, 409, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 113, 9 },  /* 409 STEP:9 */
	{ 1.50f, 61, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 114, 0 },  /* 410 STONE */
	{ 1.50f, 411, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 114, 1 },  /* 411 STONE:1 */
	{ 1.50f, 412, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 114, 2 },  /* 412 STONE:2 */
	{ 1.50f, 413, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 114, 3 },  /* 413 STONE:3 */
	{ 1.50f, 414, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 114, 4 },  /* 414 STONE:4 */
	{ 1.50f, 415, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 114, 5 },  /* 415 STONE:5 */
	{ 1.50f, 416, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 114, 6 },  /* 416 STONE:6 */
	{ 0.00f, 417, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 115, 1 },  /* 417 STONE_BUTTON:1 */
	{ 0.00f, 418, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 115, 2 },  /* 418 STONE_BUTTON:2 */
	{ 0.00f, 419, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 115, 3 },  /* 419 STONE_BUTTON:3 */
	{ 0.00f, 420, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 115, 4 },  /* 420 STONE_BUTTON:4 */
	{ 0.00f, 421, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 115, 5 },  /* 421 STONE_BUTTON:5 */
	{ 0.50f, 422, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 116, 0 },  /* 422 STONE_PLATE */
	{ 2.00f, 423, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 117, 0 },  /* 423 STONE_SLAB2 */
	{ 2.00f, 424, -1, MAT_ROCK, 1, 1, 0, 1, 1, 1, 0, 117, 8 },  /* 424 STONE_SLAB2:8 */
	{ 0.00f, 425, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 118, 1 },  /* 425 TORCH:1 */
	{ 0.00f, 426, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 118, 2 },  /* 426 TORCH:2 */
	{ 0.00f, 427, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 118, 3 },  /* 427 TORCH:3 */
	{ 0.00f, 428, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 118, 4 },  /* 428 TORCH:4 */
	{ 0.00f, 429, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 118, 5 },  /* 429 TORCH:5 */
	{ 3.00f, 430, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 0 },  /* 430 TRAP_DOOR */
	{ 3.00f, 431, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 1 },  /* 431 TRAP_DOOR:1 */
	{ 3.00f, 432, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 10 },  /* 432 TRAP_DOOR:10 */
	{ 3.00f, 433, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 11 },  /* 433 TRAP_DOOR:11 */
	{ 3.00f, 434, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 12 },  /* 434 TRAP_DOOR:12 */
	{ 3.00f, 435, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 13 },  /* 435 TRAP_DOOR:13 */
	{ 3.00f, 436, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 14 },  /* 436 TRAP_DOOR:14 */
	{ 3.00f, 437, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 15 },  /* 437 TRAP_DOOR:15 */
	{ 3.00f, 438, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 2 },  /* 438 TRAP_DOOR:2 */
	{ 3.00f, 439, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 3 },  /* 439 TRAP_DOOR:3 */
	{ 3.00f, 440, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 4 },  /* 440 TRAP_DOOR:4 */
	{ 3.00f, 441, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 5 },  /* 441 TRAP_DOOR:5 */
	{ 3.00f, 442, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 6 },  /* 442 TRAP_DOOR:6 */
	{ 3.00f, 443, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 7 },  /* 443 TRAP_DOOR:7 */
	{ 3.00f, 444, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 8 },  /* 444 TRAP_DOOR:8 */
	{ 3.00f, 445, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 119, 9 },  /* 445 TRAP_DOOR:9 */
	{ 0.00f, 446, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 120, 0 },  /* 446 TRIPWIRE_HOOK */
	{ 0.00f, 447, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 120, 1 },  /* 447 TRIPWIRE_HOOK:1 */
	{ 0.00f, 448, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 120, 2 },  /* 448 TRIPWIRE_HOOK:2 */
	{ 0.00f, 449, -1, MAT_CIRCUITS, 0, 0, 0, 1, 1, 1, 0, 120, 3 },  /* 449 TRIPWIRE_HOOK:3 */
	{ 0.20f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 121, 1 },  /* 450 VINE:1 */
	{ 0.20f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 121, 10 },  /* 451 VINE:10 */
	{ 0.20f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 121, 12 },  /* 452 VINE:12 */
	{ 0.20f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 121, 2 },  /* 453 VINE:2 */
	{ 0.20f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 121, 3 },  /* 454 VINE:3 */
	{ 0.20f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 121, 4 },  /* 455 VINE:4 */
	{ 0.20f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 121, 8 },  /* 456 VINE:8 */
	{ 0.20f, -1, -1, MAT_VINE, 2, 0, 0, 0, 0, 1, 1, 121, 9 },  /* 457 VINE:9 */
	{ 1.00f, ITEM_SIGN_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 122, 2 },  /* 458 WALL_SIGN:2 */
	{ 1.00f, ITEM_SIGN_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 122, 3 },  /* 459 WALL_SIGN:3 */
	{ 1.00f, ITEM_SIGN_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 122, 4 },  /* 460 WALL_SIGN:4 */
	{ 1.00f, ITEM_SIGN_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 122, 5 },  /* 461 WALL_SIGN:5 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 1 },  /* 462 WATER:1 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 10 },  /* 463 WATER:10 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 11 },  /* 464 WATER:11 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 12 },  /* 465 WATER:12 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 13 },  /* 466 WATER:13 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 14 },  /* 467 WATER:14 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 15 },  /* 468 WATER:15 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 2 },  /* 469 WATER:2 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 3 },  /* 470 WATER:3 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 4 },  /* 471 WATER:4 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 5 },  /* 472 WATER:5 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 6 },  /* 473 WATER:6 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 7 },  /* 474 WATER:7 */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 9 },  /* 475 WATER:9 */
	{ 0.00f, 476, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 124, 0 },  /* 476 WATER_LILY */
	{ 4.00f, ITEM_STRING_TILE, -1, MAT_WEB, 0, 4, 0, 1, 1, 1, 0, 125, 0 },  /* 477 WEB */
	{ 2.00f, 478, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 126, 0 },  /* 478 WOOD */
	{ 2.00f, 479, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 126, 1 },  /* 479 WOOD:1 */
	{ 2.00f, 480, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 126, 2 },  /* 480 WOOD:2 */
	{ 2.00f, 481, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 126, 3 },  /* 481 WOOD:3 */
	{ 2.00f, 482, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 126, 4 },  /* 482 WOOD:4 */
	{ 2.00f, 483, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 126, 5 },  /* 483 WOOD:5 */
	{ 3.00f, ITEM_DOOR_WOOD_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 127, 1 },  /* 484 WOODEN_DOOR:1 */
	{ 3.00f, ITEM_DOOR_WOOD_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 127, 2 },  /* 485 WOODEN_DOOR:2 */
	{ 3.00f, ITEM_DOOR_WOOD_TILE, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 127, 8 },  /* 486 WOODEN_DOOR:8 */
	{ 0.50f, 487, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 128, 4 },  /* 487 WOOD_BUTTON:4 */
	{ 2.00f, 503, -1, MAT_WOOD, 2, 0, 0, 2, 2, 1, 0, 129, 0 },  /* 488 WOOD_DOUBLE_STEP */
	{ 2.00f, 504, -1, MAT_WOOD, 2, 0, 0, 2, 2, 1, 0, 129, 1 },  /* 489 WOOD_DOUBLE_STEP:1 */
	{ 2.00f, 509, -1, MAT_WOOD, 2, 0, 0, 2, 2, 1, 0, 129, 2 },  /* 490 WOOD_DOUBLE_STEP:2 */
	{ 2.00f, 510, -1, MAT_WOOD, 2, 0, 0, 2, 2, 1, 0, 129, 3 },  /* 491 WOOD_DOUBLE_STEP:3 */
	{ 2.00f, 511, -1, MAT_WOOD, 2, 0, 0, 2, 2, 1, 0, 129, 4 },  /* 492 WOOD_DOUBLE_STEP:4 */
	{ 2.00f, 512, -1, MAT_WOOD, 2, 0, 0, 2, 2, 1, 0, 129, 5 },  /* 493 WOOD_DOUBLE_STEP:5 */
	{ 0.50f, 494, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 130, 0 },  /* 494 WOOD_PLATE */
	{ 2.00f, 495, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 131, 0 },  /* 495 WOOD_STAIRS */
	{ 2.00f, 496, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 131, 1 },  /* 496 WOOD_STAIRS:1 */
	{ 2.00f, 497, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 131, 2 },  /* 497 WOOD_STAIRS:2 */
	{ 2.00f, 498, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 131, 3 },  /* 498 WOOD_STAIRS:3 */
	{ 2.00f, 499, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 131, 4 },  /* 499 WOOD_STAIRS:4 */
	{ 2.00f, 500, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 131, 5 },  /* 500 WOOD_STAIRS:5 */
	{ 2.00f, 501, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 131, 6 },  /* 501 WOOD_STAIRS:6 */
	{ 2.00f, 502, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 131, 7 },  /* 502 WOOD_STAIRS:7 */
	{ 2.00f, 503, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 0 },  /* 503 WOOD_STEP */
	{ 2.00f, 504, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 1 },  /* 504 WOOD_STEP:1 */
	{ 2.00f, 505, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 10 },  /* 505 WOOD_STEP:10 */
	{ 2.00f, 506, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 11 },  /* 506 WOOD_STEP:11 */
	{ 2.00f, 507, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 12 },  /* 507 WOOD_STEP:12 */
	{ 2.00f, 508, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 13 },  /* 508 WOOD_STEP:13 */
	{ 2.00f, 509, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 2 },  /* 509 WOOD_STEP:2 */
	{ 2.00f, 510, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 3 },  /* 510 WOOD_STEP:3 */
	{ 2.00f, 511, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 4 },  /* 511 WOOD_STEP:4 */
	{ 2.00f, 512, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 5 },  /* 512 WOOD_STEP:5 */
	{ 2.00f, 513, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 8 },  /* 513 WOOD_STEP:8 */
	{ 2.00f, 514, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 132, 9 },  /* 514 WOOD_STEP:9 */
	{ 0.80f, 515, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 0 },  /* 515 WOOL */
	{ 0.80f, 516, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 1 },  /* 516 WOOL:1 */
	{ 0.80f, 517, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 10 },  /* 517 WOOL:10 */
	{ 0.80f, 518, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 11 },  /* 518 WOOL:11 */
	{ 0.80f, 519, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 12 },  /* 519 WOOL:12 */
	{ 0.80f, 520, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 13 },  /* 520 WOOL:13 */
	{ 0.80f, 521, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 14 },  /* 521 WOOL:14 */
	{ 0.80f, 522, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 15 },  /* 522 WOOL:15 */
	{ 0.80f, 523, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 2 },  /* 523 WOOL:2 */
	{ 0.80f, 524, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 3 },  /* 524 WOOL:3 */
	{ 0.80f, 525, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 4 },  /* 525 WOOL:4 */
	{ 0.80f, 526, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 5 },  /* 526 WOOL:5 */
	{ 0.80f, 527, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 6 },  /* 527 WOOL:6 */
	{ 0.80f, 528, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 7 },  /* 528 WOOL:7 */
	{ 0.80f, 529, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 8 },  /* 529 WOOL:8 */
	{ 0.80f, 530, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 133, 9 },  /* 530 WOOL:9 */
	{ 2.50f, 531, -1, MAT_WOOD, 2, 0, 0, 1, 1, 1, 0, 134, 0 },  /* 531 WORKBENCH */
	{ 0.00f, 532, -1, MAT_PLANTS, 2, 0, 0, 1, 1, 1, 0, 135, 0 },  /* 532 YELLOW_FLOWER */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 0 },  /* 533 WATER */
	{ 100.00f, -1, -1, MAT_WATER, 0, 0, 0, 0, 0, 1, 1, 123, 8 },  /* 534 WATER:8 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 0 },  /* 535 LAVA */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 1 },  /* 536 LAVA:1 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 2 },  /* 537 LAVA:2 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 3 },  /* 538 LAVA:3 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 4 },  /* 539 LAVA:4 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 5 },  /* 540 LAVA:5 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 6 },  /* 541 LAVA:6 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 7 },  /* 542 LAVA:7 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 8 },  /* 543 LAVA:8 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 9 },  /* 544 LAVA:9 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 10 },  /* 545 LAVA:10 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 11 },  /* 546 LAVA:11 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 12 },  /* 547 LAVA:12 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 13 },  /* 548 LAVA:13 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 14 },  /* 549 LAVA:14 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 136, 15 },  /* 550 LAVA:15 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 0 },  /* 551 STATIONARY_LAVA */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 1 },  /* 552 STATIONARY_LAVA:1 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 2 },  /* 553 STATIONARY_LAVA:2 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 3 },  /* 554 STATIONARY_LAVA:3 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 4 },  /* 555 STATIONARY_LAVA:4 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 5 },  /* 556 STATIONARY_LAVA:5 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 6 },  /* 557 STATIONARY_LAVA:6 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 7 },  /* 558 STATIONARY_LAVA:7 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 8 },  /* 559 STATIONARY_LAVA:8 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 9 },  /* 560 STATIONARY_LAVA:9 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 10 },  /* 561 STATIONARY_LAVA:10 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 11 },  /* 562 STATIONARY_LAVA:11 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 12 },  /* 563 STATIONARY_LAVA:12 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 13 },  /* 564 STATIONARY_LAVA:13 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 14 },  /* 565 STATIONARY_LAVA:14 */
	{ 100.00f, -1, -1, MAT_LAVA, 0, 0, 0, 0, 0, 1, 1, 137, 15 },  /* 566 STATIONARY_LAVA:15 */
	{ 0.00f, 567, -1, MAT_CLOTH, 0, 0, 0, 1, 1, 1, 0, 138, 0 },  /* 567 TNT */
	{ -1.00f, -1, -1, MAT_ROCK, 1, 1, 0, 0, 0, 1, 0, 139, 0 },  /* 568 UNKNOWN_BLOCK */
};

#define NUM_BLOCK_FAMILIES 140

/* How each family reacts to being placed (PLACE_*). */
static const u8 g_familyPlace[NUM_BLOCK_FAMILIES] = {
0,1,8,0,0,0,7,1,0,0,0,1,0,0,0,5,0,0,0,0,1,0,0,0,0,7,1,0,0,0,0,0,0,5,0,0,7,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6,0,0,0,0,3,3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,7,1,0,0,0,0,2,0,0,0,2,4,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,5,0,0,0,0,0
};

/* family x data value -> global block id, -1 when that variant
 * never appeared in any scanned map (so it has no id here). Lets
 * placement re-derive an id after Block.onBlockPlaced picks a new
 * data value; a -1 means 'keep the id that was picked up'. */
static const s16 g_blockVariant[NUM_BLOCK_FAMILIES][16] = {
	{0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* ACACIA_FENCE */
	{1,2,3,4,5,6,7,8,-1,-1,-1,-1,-1,-1,-1,-1},  /* ACACIA_STAIRS */
	{9,10,11,12,-1,13,-1,14,-1,15,-1,-1,-1,-1,-1,-1},  /* ANVIL */
	{16,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* BEDROCK */
	{-1,17,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* BED_BLOCK */
	{18,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* BIRCH_FENCE */
	{-1,19,20,21,22,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* BIRCH_FENCE_GATE */
	{23,24,25,26,27,28,29,30,-1,-1,-1,-1,-1,-1,-1,-1},  /* BIRCH_WOOD_STAIRS */
	{31,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* BOOKSHELF */
	{32,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* BREWING_STAND */
	{33,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* BRICK */
	{34,35,36,37,38,39,40,41,-1,-1,-1,-1,-1,-1,-1,-1},  /* BRICK_STAIRS */
	{42,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* BROWN_MUSHROOM */
	{43,44,-1,49,-1,-1,-1,-1,50,51,-1,45,46,47,48,-1},  /* CARPET */
	{52,-1,-1,53,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* CAULDRON */
	{-1,-1,54,55,56,57,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* CHEST */
	{58,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* CLAY */
	{59,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* COAL_BLOCK */
	{60,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* COAL_ORE */
	{61,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* COBBLESTONE */
	{62,63,64,65,66,67,68,69,-1,-1,-1,-1,-1,-1,-1,-1},  /* COBBLESTONE_STAIRS */
	{70,71,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* COBBLE_WALL */
	{72,73,76,77,78,79,80,81,82,83,74,75,-1,-1,-1,-1},  /* COCOA */
	{-1,-1,-1,-1,-1,-1,-1,84,-1,-1,-1,-1,-1,-1,-1,-1},  /* CROPS */
	{85,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* DARK_OAK_FENCE */
	{86,87,88,89,90,91,92,93,-1,-1,-1,-1,-1,-1,-1,-1},  /* DARK_OAK_FENCE_GATE */
	{94,95,96,97,98,99,100,101,-1,-1,-1,-1,-1,-1,-1,-1},  /* DARK_OAK_STAIRS */
	{102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* DEAD_BUSH */
	{103,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* DIAMOND_BLOCK */
	{104,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* DIAMOND_ORE */
	{105,106,107,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* DIRT */
	{-1,-1,-1,109,110,-1,-1,-1,-1,-1,108,-1,-1,-1,-1,-1},  /* DOUBLE_PLANT */
	{111,112,-1,115,-1,116,117,118,119,120,-1,113,-1,114,-1,-1},  /* DOUBLE_STEP */
	{-1,121,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,122,-1,-1},  /* DROPPER */
	{123,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* ENCHANTMENT_TABLE */
	{124,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* FENCE */
	{-1,125,126,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* FENCE_GATE */
	{-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,127},  /* FIRE */
	{-1,-1,128,129,130,131,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* FURNACE */
	{132,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* GLASS */
	{133,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* GLOWSTONE */
	{134,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* GOLD_BLOCK */
	{135,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* GOLD_ORE */
	{136,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* GRASS */
	{137,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* GRAVEL */
	{138,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* HARD_CLAY */
	{139,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* HAY_BLOCK */
	{140,-1,141,142,143,144,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* HOPPER */
	{-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,145,-1,-1,-1,146,-1},  /* HUGE_MUSHROOM_1 */
	{-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,147,148},  /* HUGE_MUSHROOM_2 */
	{149,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* ICE */
	{150,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* IRON_BLOCK */
	{151,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* IRON_FENCE */
	{152,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* IRON_ORE */
	{153,154,157,158,-1,-1,-1,-1,-1,-1,-1,-1,155,156,-1,-1},  /* IRON_TRAPDOOR */
	{159,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* JUKEBOX */
	{-1,-1,-1,-1,-1,-1,-1,-1,-1,160,-1,-1,-1,-1,-1,-1},  /* JUNGLE_DOOR */
	{161,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* JUNGLE_FENCE */
	{162,163,164,165,166,167,168,169,-1,-1,-1,-1,-1,-1,-1,-1},  /* JUNGLE_WOOD_STAIRS */
	{-1,-1,170,171,172,173,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* LADDER */
	{174,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* LAPIS_BLOCK */
	{175,-1,-1,181,182,183,184,185,186,-1,-1,176,177,178,179,180},  /* LEAVES */
	{-1,-1,-1,-1,-1,188,-1,-1,-1,-1,-1,-1,-1,187,-1,-1},  /* LEAVES_2 */
	{-1,-1,-1,-1,-1,-1,194,-1,-1,-1,189,-1,190,191,192,193},  /* LEVER */
	{195,196,-1,201,202,203,-1,204,205,206,-1,197,198,199,-1,200},  /* LOG */
	{207,208,-1,-1,211,212,-1,-1,213,214,-1,-1,209,210,-1,-1},  /* LOG_2 */
	{-1,215,216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* LONG_GRASS */
	{217,-1,218,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* MONSTER_EGGS */
	{219,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* MOSSY_COBBLESTONE */
	{220,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* MYCEL */
	{221,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* NETHERRACK */
	{222,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* NETHER_BRICK */
	{223,224,225,226,227,228,229,230,-1,-1,-1,-1,-1,-1,-1,-1},  /* NETHER_BRICK_STAIRS */
	{231,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* NETHER_FENCE */
	{-1,-1,-1,232,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* NETHER_WARTS */
	{233,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* NOTE_BLOCK */
	{234,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* OBSIDIAN */
	{235,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* PACKED_ICE */
	{-1,236,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* PISTON_BASE */
	{-1,-1,241,242,243,244,-1,-1,245,246,237,238,239,240,-1,-1},  /* POWERED_RAIL */
	{247,-1,248,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* PRISMARINE */
	{249,250,251,252,253,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* QUARTZ_BLOCK */
	{254,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* QUARTZ_ORE */
	{255,256,257,258,259,260,261,262,-1,-1,-1,-1,-1,-1,-1,-1},  /* QUARTZ_STAIRS */
	{-1,-1,-1,-1,-1,-1,263,264,265,266,-1,-1,-1,-1,-1,-1},  /* RAILS */
	{267,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* REDSTONE_BLOCK */
	{268,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* REDSTONE_LAMP_ON */
	{269,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* REDSTONE_WIRE */
	{270,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* RED_MUSHROOM */
	{271,272,273,274,-1,-1,-1,275,-1,-1,-1,-1,-1,-1,-1,-1},  /* RED_ROSE */
	{276,277,278,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* RED_SANDSTONE */
	{-1,-1,-1,-1,-1,-1,279,280,-1,-1,-1,-1,-1,-1,-1,-1},  /* RED_SANDSTONE_STAIRS */
	{281,282,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SAND */
	{283,284,285,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SANDSTONE */
	{286,287,288,289,290,291,292,293,-1,-1,-1,-1,-1,-1,-1,-1},  /* SANDSTONE_STAIRS */
	{294,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SEA_LANTERN */
	{-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,295,-1,-1,-1},  /* SIGN_POST */
	{-1,296,-1,297,298,299,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SKULL */
	{300,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SLIME_BLOCK */
	{301,302,303,304,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SMOOTH_BRICK */
	{305,306,307,308,309,310,311,312,-1,-1,-1,-1,-1,-1,-1,-1},  /* SMOOTH_STAIRS */
	{313,314,315,316,317,318,319,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SNOW */
	{320,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SNOW_BLOCK */
	{-1,-1,-1,-1,-1,-1,-1,321,-1,-1,-1,-1,-1,-1,-1,-1},  /* SOIL */
	{322,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SOUL_SAND */
	{323,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SPONGE */
	{324,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* SPRUCE_FENCE */
	{325,326,327,328,-1,-1,329,330,-1,-1,-1,-1,-1,-1,-1,-1},  /* SPRUCE_FENCE_GATE */
	{331,332,333,334,335,336,337,338,-1,-1,-1,-1,-1,-1,-1,-1},  /* SPRUCE_WOOD_STAIRS */
	{339,340,347,348,349,350,351,352,353,354,341,342,343,344,345,346},  /* STAINED_CLAY */
	{355,356,362,363,364,365,366,-1,367,368,357,358,-1,359,360,361},  /* STAINED_GLASS */
	{369,370,375,376,377,378,379,380,381,-1,-1,371,-1,372,373,374},  /* STAINED_GLASS_PANE */
	{382,383,390,391,392,393,394,395,396,397,384,385,386,387,388,389},  /* STATIONARY_WATER */
	{398,399,-1,404,-1,405,406,407,408,409,-1,400,-1,401,402,403},  /* STEP */
	{410,411,412,413,414,415,416,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* STONE */
	{-1,417,418,419,420,421,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* STONE_BUTTON */
	{422,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* STONE_PLATE */
	{423,-1,-1,-1,-1,-1,-1,-1,424,-1,-1,-1,-1,-1,-1,-1},  /* STONE_SLAB2 */
	{-1,425,426,427,428,429,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* TORCH */
	{430,431,438,439,440,441,442,443,444,445,432,433,434,435,436,437},  /* TRAP_DOOR */
	{446,447,448,449,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* TRIPWIRE_HOOK */
	{-1,450,453,454,455,-1,-1,-1,456,457,451,-1,452,-1,-1,-1},  /* VINE */
	{-1,-1,458,459,460,461,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* WALL_SIGN */
	{533,462,469,470,471,472,473,474,534,475,463,464,465,466,467,468},  /* WATER */
	{476,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* WATER_LILY */
	{477,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* WEB */
	{478,479,480,481,482,483,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* WOOD */
	{-1,484,485,-1,-1,-1,-1,-1,486,-1,-1,-1,-1,-1,-1,-1},  /* WOODEN_DOOR */
	{-1,-1,-1,-1,487,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* WOOD_BUTTON */
	{488,489,490,491,492,493,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* WOOD_DOUBLE_STEP */
	{494,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* WOOD_PLATE */
	{495,496,497,498,499,500,501,502,-1,-1,-1,-1,-1,-1,-1,-1},  /* WOOD_STAIRS */
	{503,504,509,510,511,512,-1,-1,513,514,505,506,507,508,-1,-1},  /* WOOD_STEP */
	{515,516,523,524,525,526,527,528,529,530,517,518,519,520,521,522},  /* WOOL */
	{531,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* WORKBENCH */
	{532,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* YELLOW_FLOWER */
	{535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550},  /* LAVA */
	{551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566},  /* STATIONARY_LAVA */
	{567,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* TNT */
	{568,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},  /* UNKNOWN_BLOCK */
};

#endif
