/* Generated by tools/build_atlas.py -- do not edit. */
#ifndef MSW_BLOCK_BOOK_GEN_H
#define MSW_BLOCK_BOOK_GEN_H

/* Atlas tile for the enchanting table's static floating book
 * (mesh_enchant_table in block_shapes.c). */
#define ENCHANT_BOOK_TILE 628

#endif
