/* Generated by tools/build_entity_tex.py -- do not edit. */
#ifndef MSW_ENTITY_TEX_GEN_H
#define MSW_ENTITY_TEX_GEN_H

/* Sheet dimensions for the entity skins baked to RGB5A3 as
 * data/steve.tpl and data/dragon.tpl. entity.c's box UVs are
 * vanilla's pixel offsets into these exact sheets. */
#define DRAGON_TEX_W 256
#define DRAGON_TEX_H 256
#define STEVE_TEX_W 64
#define STEVE_TEX_H 64

#endif
