/* Generated by tools/build_font.py -- do not edit. */
#ifndef MSW_FONT_GEN_H
#define MSW_FONT_GEN_H

/* Minecraft 1.8.9's ascii.png, baked to I4 as data/font.tpl.
 * A character's cell index is its own code for the printable
 * ASCII range below -- see tools/build_font.py. */
#define FONT_CELL 8
#define FONT_GRID 16
#define FONT_TEX_W 128
#define FONT_TEX_H 128
#define FONT_FIRST_CHAR 32
#define FONT_LAST_CHAR 126
#define FONT_CHAR_COUNT 95

/* FontRenderer.charWidth: the pen advance for each glyph,
 * indexed by (char - FONT_FIRST_CHAR). Includes the 1px gap
 * the renderer leaves between glyphs; the drawn quad is always
 * FONT_CELL wide, so a glyph may overhang its own advance. */
static const u8 g_fontWidth[FONT_CHAR_COUNT] = {
	4,2,5,6,6,6,6,3,5,5,5,6,2,6,2,6,6,6,6,6,6,6,6,6,
	6,6,2,2,5,6,5,6,7,6,6,6,6,6,6,6,6,4,6,6,6,6,6,6,
	6,6,6,6,6,6,6,6,6,6,6,4,6,4,6,6,3,6,6,6,6,6,5,6,
	6,2,6,5,3,6,6,6,6,6,6,6,4,6,6,6,6,6,6,5,2,5,7,
};

#endif
