/* Generated by tools/gen_model_gallery.py -- do not edit. */
#ifndef MSW_GALLERY_TOUR_GEN_H
#define MSW_GALLERY_TOUR_GEN_H

#include "camera.h"

#define GALLERY_ROW_SLAB 0
#define GALLERY_ROW_STAIRS 1
#define GALLERY_ROW_FENCE 2
#define GALLERY_ROW_FENCE_GATE 3
#define GALLERY_ROW_WALL 4
#define GALLERY_ROW_PANE 5
#define GALLERY_ROW_ANVIL 6
#define GALLERY_ROW_ENCHANT_TABLE 7
#define GALLERY_ROW_TRAPDOOR 8
#define GALLERY_ROW_DOOR 9
#define GALLERY_ROW_OVERVIEW 10

#define GALLERY_TOUR_COUNT 11

static const CamKeyframe g_galleryTour[GALLERY_TOUR_COUNT] = {
	{ 2.00f, 10.64f, 7.20f, 0.00f, -32.00f, "slab" },
	{ 14.00f, 14.48f, 26.40f, 0.00f, -32.00f, "stairs" },
	{ 4.00f, 11.28f, 21.40f, 0.00f, -32.00f, "fence" },
	{ 8.00f, 12.56f, 31.80f, 0.00f, -32.00f, "fence_gate" },
	{ 6.00f, 11.92f, 35.60f, 0.00f, -32.00f, "wall" },
	{ 6.00f, 11.92f, 41.60f, 0.00f, -32.00f, "pane" },
	{ 12.00f, 13.84f, 54.20f, 0.00f, -32.00f, "anvil" },
	{ 0.00f, 10.00f, 47.00f, 0.00f, -32.00f, "enchant_table" },
	{ 42.00f, 23.44f, 99.20f, 0.00f, -32.00f, "trapdoor" },
	{ 6.00f, 11.92f, 65.60f, 0.00f, -32.00f, "door" },
	{ 40.00f, 69.29f, 27.00f, 0.00f, -85.00f, "overview" },
};

#endif
