/* Generated by tools/compress_worlds.py -- do not edit. */
#ifndef MSW_MAPS_GEN_H
#define MSW_MAPS_GEN_H

#include "maps.h"

#include "anchored_mworld.h"
#include "aqueduct_mworld.h"
#include "arx_citadel_mworld.h"
#include "checkmate_mworld.h"
#include "drainage_mworld.h"
#include "dryland_mworld.h"
#include "dwarf_fortress_mworld.h"
#include "elven_towers_mworld.h"
#include "finale_mworld.h"
#include "frost_mworld.h"
#include "hontori_mworld.h"
#include "krusty_krab_mworld.h"
#include "maereen_mworld.h"
#include "magnolite_mworld.h"
#include "marooned_mworld.h"
#include "mega_aegis_mworld.h"
#include "mega_martian_mworld.h"
#include "mega_shaohao_mworld.h"
#include "mega_shire_mworld.h"
#include "model_gallery_mworld.h"
#include "northern_mworld.h"
#include "oasis_mworld.h"
#include "oasisv2_mworld.h"
#include "onset_mworld.h"
#include "peak_mworld.h"
#include "renaissance_mworld.h"
#include "sandbox_mworld.h"
#include "scrapyard_mworld.h"
#include "shrooms_mworld.h"
#include "sky_carnival_mworld.h"
#include "templar_mworld.h"
#include "tundric_mworld.h"

static const MapEntry g_maps[] = {
	{ "Anchored", anchored_mworld, anchored_mworld_end, 148614 },
	{ "Aqueduct", aqueduct_mworld, aqueduct_mworld_end, 177698 },
	{ "Arx Citadel", arx_citadel_mworld, arx_citadel_mworld_end, 283167 },
	{ "Checkmate", checkmate_mworld, checkmate_mworld_end, 72517 },
	{ "Drainage", drainage_mworld, drainage_mworld_end, 160724 },
	{ "Dryland", dryland_mworld, dryland_mworld_end, 178172 },
	{ "Dwarf Fortress", dwarf_fortress_mworld, dwarf_fortress_mworld_end, 118006 },
	{ "Elven Towers", elven_towers_mworld, elven_towers_mworld_end, 84456 },
	{ "Finale", finale_mworld, finale_mworld_end, 89132 },
	{ "Frost", frost_mworld, frost_mworld_end, 192314 },
	{ "Hontori", hontori_mworld, hontori_mworld_end, 306666 },
	{ "Krusty Krab", krusty_krab_mworld, krusty_krab_mworld_end, 133165 },
	{ "Maereen", maereen_mworld, maereen_mworld_end, 160904 },
	{ "Magnolite", magnolite_mworld, magnolite_mworld_end, 122610 },
	{ "Marooned", marooned_mworld, marooned_mworld_end, 201236 },
	{ "Mega Aegis", mega_aegis_mworld, mega_aegis_mworld_end, 393278 },
	{ "Mega Martian", mega_martian_mworld, mega_martian_mworld_end, 239347 },
	{ "Mega Shaohao", mega_shaohao_mworld, mega_shaohao_mworld_end, 223564 },
	{ "Mega Shire", mega_shire_mworld, mega_shire_mworld_end, 120950 },
	{ "Model Gallery", model_gallery_mworld, model_gallery_mworld_end, 5266 },
	{ "Northern", northern_mworld, northern_mworld_end, 53179 },
	{ "Oasis", oasis_mworld, oasis_mworld_end, 81101 },
	{ "Oasisv2", oasisv2_mworld, oasisv2_mworld_end, 107021 },
	{ "Onset", onset_mworld, onset_mworld_end, 137434 },
	{ "Peak", peak_mworld, peak_mworld_end, 82798 },
	{ "Renaissance", renaissance_mworld, renaissance_mworld_end, 176266 },
	{ "Sandbox", sandbox_mworld, sandbox_mworld_end, 133132 },
	{ "Scrapyard", scrapyard_mworld, scrapyard_mworld_end, 48106 },
	{ "Shrooms", shrooms_mworld, shrooms_mworld_end, 176897 },
	{ "Sky Carnival", sky_carnival_mworld, sky_carnival_mworld_end, 187224 },
	{ "Templar", templar_mworld, templar_mworld_end, 148307 },
	{ "Tundric", tundric_mworld, tundric_mworld_end, 186889 },
};

#define MAP_COUNT ((int)(sizeof(g_maps)/sizeof(g_maps[0])))

#endif
